config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "photos#index"
  resources :photos
  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :file_location, PhotoImageUploader 
  validates_presence_of :title, :date, :description, :file_location
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/application_controller.rb
class Api::ApplicationController < ActionController::Base

  before_action :authenticate_user_from_token!

  def authenticate_user_from_token!

    if params[:auth_token].present?
      user = User.find_by_authentication_token(
                  params[:auth_token] )

      # Devise: 設定 current_user
      sign_in(user, store: false) if user
    end

  end
  
end

app/controllers/api/auth_controller.rb
class Api::AuthController < Api::ApplicationController

  before_action :authenticate_user!, :only => [:logout]

  def login
      success = false

      if params[:email] && params[:password]
        user = User.find_by_email( params[:email] )
        success = user && user.valid_password?( params[:password] )
      end

      if success
        render json:  { message: "Ok",
                          auth_token:  user.authentication_token,
                          user_id:  user.id}
      else
        render json:  { message:  "Email or Password is wrong" }, status:  401
      end
    end

  def logout
    current_user.generate_authentication_token
    current_user.save!

    render json:  { message:  "Ok"}
  end

end

app/controllers/api/photos_controller.rb
class Api::PhotosController < Api::ApplicationController
  before_action :set_photo, :only => [:show, :update, :destroy]

  def index
    @photos = Photo.all
    respond_to do |format|
      format.json { render json: @photos }
    end
  end

  def create
    @photo = Photo.create(photo_params)
    if @photo.save
      render json: {
        message: "success create pohoto!!"
      }
    else
      render json: {
        errors: @photo.errors
      }
    end
  end

  def update
    if @photo.update(photo_params)
      respond_to do |format|
        format.json { render json: @photo }
      end
    else
      render json:{
        errors: @photo.errors
      }
    end
  end

  def destroy
    if @photo.destroy
      render json:{
        message: "success to delete! "
      }
    else
      render json: {
        message: "Can't delete!"
      }
    end
  end

  def all
    month  =  params[:month].to_i
    url = params[:only]
    @photos = Photo.where("cast(strftime('%m', date) as int) = ?", month)
    if url
      return render json: {
        file_location: @photos.map{|photo|  photo.file_location}
      }

    else
      return respond_to do |format|
        format.json { render json: @photos }
      end
    end
  end

  def random
    rand_count = params[:rand]
    url = params[:only]
    @photos = Photo.limit(rand_count).order("random()")
    if url
      return render json: {
        file_location: @photos.map{|photo|  photo.file_location}
      }

    else
      return respond_to do |format|
        format.json { render json: @photos }
      end
    end
  end



  private

  def photo_params
    params.permit(:title, :date, :description, :file_location)
  end

  def set_photo
    @photo = Photo.find(params[:id])
  end


end

app/controllers/api/users_controller.rb
class Api::UsersController < Api::ApplicationController


  def index

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_photo, :only => [:show, :edit, :update, :destroy]

  def index
    @photos = Photo.all
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    if @photo.save
      redirect_to photos_path
    else
      render :action => :new
    end
  end

  def update
    if @photo.update(photo_params)
      redirect_to photo_path(@photo)
    else
      render :action => :edit
    end
  end

  def destroy
    @photo.destroy

    redirect_to photos_path
  end

  private

  def set_photo
    @photo = Photo.find(params[:id])
  end

  def photo_params
    params.require(:photo).permit(:title, :date, :description, :file_location)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoAlbum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to "我的家庭相簿", root_path, class: "navbar-brand" %>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li><%= link_to 'All User', users_path %></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <% if current_user %>
              <li><p class="navbar-text">Hi, <%= current_user.email %></p></li>
              <li><%= link_to('登出', destroy_user_session_path, method: :delete) %></li>
              <li><%= link_to('修改密碼', edit_user_registration_path) %></li>
              <% else %>
              <li><%= link_to('註冊', new_user_registration_path) %></li>
              <li><%= link_to('登入', new_user_session_path) %></li>
              <% end %>
            </ul>
          </div>

        </div><!-- /.container-fluid -->
      </nav>

      <% if flash[:notice] %>
        <div class="alert alert-success" role="alert"><%= notice %></div>
      <% elsif flash[:alert] %>
        <div class="alert alert-danger" role="alert"><%= alert %></div>
      <% end %>
      <%= yield %>
    <div>
  </body>
</html>

app/views/photos/_form.html.erb
<% if @photo.errors.present? %>
  <ul>
    <% @photo.errors.each do |error, message| %>
      <li> <%= "#{error.capitalize}  #{message}" %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @photo do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :date %>
  <%= f.text_field :date %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :file_location %>
  <%= f.file_field :file_location %>

  <%= f.submit %>
<% end %>

app/views/photos/edit.html.erb
<%= render partial: "form" %>

app/views/photos/index.html.erb
<ul>
 <% @photos.each do |photo| %>
   <li>
     <%= photo.title %>
     <%= link_to 'Show', photo_path(photo) %>
     <%= link_to 'Edit', edit_photo_path(photo) %>
     <%= link_to 'Destroy', photo_path(photo), method: :delete, data:{ confirm: "Are you sure?" } %>
   </li>
 <% end %>
</ul>

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<%= render partial: "form" %>

app/views/photos/show.html.erb
<h3><%= @photo.title %></h3>

<%= @photo.date %><br>
<%= image_tag @photo.file_location %><br>
<%= simple_format(@photo.description) %>

<p><%= link_to 'Back to index', photos_path %></p>

app/views/users/index.html.erb
<h1>All User</h1>

<table class="table">
  <tr>
    <th>Avatar</th>
    <th>Name</th>
    <th>Email</th>
    <th>Gender</th>
    <th>Age</th>
    <th>Phone</th>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= image_tag user.avatar if user.avatar? %></td>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= user.gender %></td>
      <td><%= user.age %></td>
      <td><%= user.phone %></td>
    </tr>
  <% end %>
</table>